#!/bin/bash

# Since this is used as an npx command, first
# we need to install all the dependencies and
# add the bins to that PATH.
# 1. get the path of this actual file
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR
cd ..
cd lib/node_modules/an11ty
# 2. install pinned dependencies
npm i
# 3. add to path
ACTUALDIR=`pwd`
PATH=$PATH:$ACTUALDIR/node_modules/.bin

function watch_site () {
	echo 'Watching site folder for changes...'
	npx chokidar-cli "site/**" -c "npx ncp ./site ./_copy"
}

function watch_eleventy () {
	cd _copy
	npm run serve
}

function build () {
	echo 'Cleaning old copy...'
	rm -rf _copy
	echo "Grabbing a copy of $1..."
	npx degit "$1" _copy
	echo "Merging your site in..."
	npx ncp ./site ./_copy
	echo "Installing all dependencies..."
	cd _copy
	npm ci
	echo "Finally building..."
	npm run build
}

function dev () {
	echo 'If the _copy does not exist, you will need to run "build" first.'
	# https://stackoverflow.com/questions/3004811/how-do-you-run-multiple-programs-in-parallel-from-a-bash-script
	(trap 'kill 0' SIGINT; watch_site & watch_eleventy)
}

function demo () {
	echo 'HELLO WORLD????'
	ncp --version
}

# execute a function in the context of this scope
eval "$1"
